[global]
domainNumber            24
slaveOnly               1
time_stamping           hardware
tx_timestamp_timeout    100
logging_level           6
summary_interval        0

[ens7f0]
network_transport       L2
hybrid_e2e              0
